name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod tidy

    - name: Install Chromium dependencies (no-sandbox workaround)
      run: |
        sudo apt-get update
        sudo apt-get install -y libatk-bridge2.0-0 libgtk-3-0 libxss1 libasound2

    - name: Build CLI
      run: make build

    - name: Run example (GET)
      run: go run examples/get.go

    - name: Run example (POST)
      run: go run examples/post.go

    - name: Run linter (optional)
      run: go vet ./...

